### ISSUE TITLE
GameGlass

### ISSUE THREAD

**Issue by jknash101** [spliffz/X52Elite_v3.3.0-beyond#6]
Any change you can make this work with GameGlass also?

**Comment by obmucm** [comment]
How do you like GameGlass? Is it worth the purchase?

**Comment by SAmundson07** [comment]
I personally haven't used game glass, but based on what I've read about their product this is just an add-on product that allows you to run control panels along side several games on the PC. If your using an X52 Pro HOTAS with the GameGlass I don't see why this wouldn't work the way it currently is.

**Comment by daniloraisi** [comment]
@jknash101 I'm a new user of Elite Dangerous. I have X52 Pro configured and working and also GameGlass. You need to note the key bindings created by @SAmundson07 and then change them under the GameGlass Desktop server configuration.
